### ISSUE TITLE
[BUG]: `<>=` not caught by keyword linter

### ISSUE THREAD

**Issue by winstonallo** [42-Short/rust#5]

**Comment by bgebetsb** [comment]
I just investigated a bit because I was curious... The cause is the `\b` in this regex to check word for word boundaries:
https://github.com/42-Short/rust/blob/6d6d6c2d2b2d4d06ce6c436b1c5acf210dd0f046/internal/alloweditems/alloweditems.go#L52

**Comment by bgebetsb** [comment]
The problem with completely removing the `\b` is that it would also match keywords that are part of a longer word, let's say someone is creating a variable called `return_value` if the `return` keyword is forbidden, it would also detect it.

I just opened a PR with a fix, it will add the `\b` only if its a word, so e.g. if the forbidden keywords are `<`, `>`, `unsafe` and `return`, the regex would end up being `(<|>|\bunsafe\b|\breturn\b)`

**Comment by winstonallo** [comment]
#6
